export { tokenize } from "./tokenize";
export {
  parse,
  ROOT_NODE,
  ELEMENT_NODE,
  TEXT_NODE,
  EXPRESSION_NODE,
  BOOLEAN_PROP,
  STRING_PROP,
  EXPRESSION_PROP,
  SPREAD_PROP,
  type RootNode,
  type ElementNode,
  type TextNode,
  type ExpressionNode,
  type ChildNode,
  type PropNode,
  type BooleanProp,
  type StringProp as StaticProp,
  type ExpressionProp,
  type SpreadProp,
} from "./parse";
